FROM docker.n8n.io/n8nio/n8n

# Opcional: establecer zona horaria
ENV GENERIC_TIMEZONE="America/Mexico_City"
ENV DB_TYPE="postgresdb"
ENV DB_POSTGRESDB_HOST="ep-damp-mode-advuk4hy-pooler.c-2.us-east-1.aws.neon.tech"
ENV DB_POSTGRESDB_PORT=5432
ENV DB_POSTGRESDB_DATABASE="neondb"
ENV DB_POSTGRESDB_USER="neondb_owner"
ENV DB_POSTGRESDB_PASSWORD="npg_NE1QDOiKJC9q"
ENV DB_POSTGRESDB_SSL_CA=true
ENV DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED=false
ENV DB_POSTGRESDB_USER="your_user"
ENV DB_TYPE=postgresdb
ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_PASSWORD="password"
ENV N8N_BASIC_AUTH_USER="your_user"
ENV N8N_BLOCK_ENV_ACCESS_IN_NODE=false
ENV N8N_ENCRYION_KEY="password_super_segura"
ENV N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
ENV N8N_RUNNERS_ENABLED=true
ENV N8N_WEBHOOK=https://n8n-koyed.onrender.com
# Puerto por defecto de n8n
EXPOSE 5678

