name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # o la rama que prefieras

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mi-imagen:latest .

      - name: Tag copy of image
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/mi-imagen:latest ${{ secrets.DOCKERHUB_USERNAME }}/mi-imagen:copia

      - name: Push both images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mi-imagen:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mi-imagen:copia
